#!/bin/bash

bash_powerline() {
  ruler=$(echo -ne '\xE2\x94\x8C'; echo -ne '\xe2\x94\x80')
  apple=$(echo -n ' '; echo -ne '\xef\xa3\xbf'; echo -n ' ')
  folder=$(echo -ne '\xEE\xAA\x83'; echo -n ' ')
  directory=${PWD/#$HOME/\~}
  branch="$(echo -ne '\xEE\x9C\xA5'; echo -n ' ')$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')"
  r_ptr=$(echo -ne '\xEE\x82\xB0')
  l_ptr=$(echo -ne '\xee\x82\xb2\x0a')
  datetime="$(date '+%Y-%m-%d %H:%M')"
  clock="$(echo -n ' '; echo -ne '\xE2\x97\xB4'; echo -n ' ')"

  echo -n "$(tput setaf 7)${ruler}"
  echo -n "$(tput setab 27)${apple}"
  echo -n "$(tput setaf 27)$(tput setab 32)${r_ptr}"
  echo -n "$(tput setaf 7)$(tput setab 32)${folder}"
  echo -n "$(tput setab 32)${directory}"
  echo -n "$(tput setaf 32)$(tput setab 37)${r_ptr}"
  echo -n "$(tput setaf 7)$(tput setab 37)${branch}"
  echo -n "$(tput sgr0)$(tput setaf 37)${r_ptr}"
  echo -n "$(tput sgr0)"

  total_char=$((${#ruler} + ${#apple} + ${#folder} + ${#clock} + ${#datetime} + ${#directory} + ${#branch} + ${#r_ptr}*4 + 1))

  separator=$(($(tput cols) - ${#ruler} - ${#apple} - ${#folder} - ${#clock} - ${#datetime} - ${#directory} - ${#branch} - ${#r_ptr}*4 - 1))

  if [ "$(tput cols)" -gt "$total_char" ]; then
    tput cuf $separator
    echo -n "$(tput setaf 2)${l_ptr}"
    echo -n "$(tput setaf 7)$(tput setab 2)${datetime}${clock}"
    echo -n "$(tput sgr0)"
  fi
}

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  PS1="\[\$(bash_powerline)\]\n\$(echo -ne '\xE2\x94\x94'; echo -ne '\xe2\x94\x80')\[\e[1;32m\]\u\[\e[0m\]@\[\e[1;31m\]\H\[\e[0m\]\\$ "
else
  PS1="\[\e[1;32m\]\u\[\e[0m\]@\[\e[1;31m\]\H\[\e[0m\]\\$ "
fi
